### PR TITLE
Rename Disco => Techno

### PR DESCRIPTION
**Pull request by sebastianfeldmann**
Bring this library from the 70s at least to the 90s ;)

### CODE REVIEW

**Comment by shochdoerfer** [comment]
The worst thing about this PR is the fact that you were able to raise the code coverage to 100%.

**Comment by sebastianfeldmann** [comment]
I knew you would appreciate the hours and hours of work I put in to this :D

**Comment by shochdoerfer** [comment]
Thank you very much for the time and effort you put into this PR, you clearly seem to love Techno. It is good to see that you found this little gem, figured out it is actually quite useful and wanted to improve it. I do really appreciate that you managed to raise code coverage to 100% and I do really appreciate your effort in changing 112 files in one go. However the latter part is the problem I have with this PR. I stayed up all night to review each and every single change and simply was not able to finish the review by this very morning. Given that, I have to say that I cannot accept this PR now or ever due to its complexity.

As a positive side effect you clearly showed that we should improve the contribution guide to highlight what an "acceptable" size of a PR this.

P.S. For gods sake, please do not turn this single PR into 112 distinct ones ;)

**Comment by shochdoerfer** [comment]
@settermjd Mind extending the contribution guide to give some guidance on how "big" a PR should be?

**Comment by settermjd** [comment]
Shall do. Sorry to only see this now.

**Pull request closed without merging**
