### PR TITLE
[WIP] Extract the docs out into a new documentation structure

### PR DESCRIPTION
**Pull request by settermjd**
This PR:

- begins the creation of a self-sustaining documentation structure
for the project. The README can then be dedicated to providing a project
introduction/overview and a table of contents (of sorts).

### CODE REVIEW

**Comment by shochdoerfer** [comment]
I started the doc migration process in #82. Feel free to continue here but you might want to have a look at the content I already created in #82.

**Comment by shochdoerfer** [comment]
Anything I can help with to drive things forward?

**Comment by shochdoerfer** [comment]
See #70 for some more improvements I would like to see, especially changes for the README.md file. We should somehow make Disco look less magical. Given the feedback I got so far is, that ppl think it is too much voodoo for basic use cases.

**Comment by settermjd** [comment]
In answer to your question, prod me every so often. Sorry.

**Comment by shochdoerfer** [comment]
@settermjd since I just merged #82, do we still need this PR?

**Comment by shochdoerfer** [comment]
@settermjd what about these changes, still relevant?

**Comment by settermjd** [comment]
At this stage, since it's been so long, I'm going to scrap them and potentially look again at them.

**Pull request closed without merging**
