### PR TITLE
Rising Code Coverage for Disco to 100%

### PR DESCRIPTION
**Pull request by SenseException**
This PR covers one step of #94: Getting 100% code coverage. I also made a few tests stricter.

During my work, I realized, that in its integration, there is still a possible unreachable code in Disco. In `BeanMethod::generateMethod()`, there is a [else-block](https://github.com/bitExpert/disco/blob/v0.8.0/src/bitExpert/Disco/Proxy/Configuration/MethodGenerator/BeanMethod.php#L100-L108) which can be tested when it is handled as a unit.

The method itself is only used in `ConfigurationGenerator` at line [167.](https://github.com/bitExpert/disco/blob/v0.8.0/src/bitExpert/Disco/Proxy/Configuration/ConfigurationGenerator.php#L167) But before it's invoked, the same checks as in [`BeanMethod::generateMethod()`](https://github.com/bitExpert/disco/blob/v0.8.0/src/bitExpert/Disco/Proxy/Configuration/MethodGenerator/BeanMethod.php#L71-L74) are also done in `ConfigurationGenerator`, which happens at line [150.](https://github.com/bitExpert/disco/blob/v0.8.0/src/bitExpert/Disco/Proxy/Configuration/ConfigurationGenerator.php#L150) It looks like the `BeanMethod::generateMethod()` else-block never can be reached during Disco's runtime.

Should I remove the else-block and its newly added test?

### CODE REVIEW

**Comment by shochdoerfer** [comment]
I know about the code duplication and to be fair I was not sure how to properly solve it. On the one hand I want to fail as early as possible and have all checks in one place but on the other hand it felt odd to not check the type in then `BeanMethod` in case someone would use the code in a different context.

If you ask me, I would prefer to remove the check in `ConfigurationGenerator` and leave it in place in the `BeanMethod` class. What do you think?

**Comment by SenseException** [comment]
In that case, I'd move the `InvalidProxiedClassException` to `BeanMethod::generateMethod()` instead of creating the BeanException-body in the else-block, in case BC is important. Creating the Proxy-Method seems to be a part of the unit, that is `ConfigurationGenerator::generate()`. Checking the types is only relevant for `$proxyMethod`, so I agree with your thought about having those checks in `BeanMethod`.

Also, `$beanType` in  `BeanMethod::generateMethod()` can only be a string, which is why we can add a string-cast to the method.

**Comment by shochdoerfer** [comment]
Sounds good to me.

**Comment by shochdoerfer** [comment]
Are you done with the PR? Can I merge it or do you want/need to add anything else?

**Comment by SenseException** [comment]
I moved the beanType logic to `BeanMethod::generateMethod()` yesterday evening. It should be ready to merge if you're okay with my changes.

**Comment by shochdoerfer** [comment]
Manually rebased and merged. Thanks for your contribution!

**Comment by SenseException** [comment]
Looks like some of the changes were not merged or the merge went wrong. `ConfigurationGenerator` still has code that was moved into another class by this PR.

**Comment by shochdoerfer** [comment]
Bummer. Thanks. Looks like the rebase & merge resulted in duplicate code. Will check. Thanks for spotting the error.

**Pull request closed without merging**
