### PR TITLE
Allow protected methods to be ignored

### PR DESCRIPTION
**Pull request by heiglandreas**
When you want to extend a global configuration with a configuration for prod or dev-environment you might need to decalre a formerly private method with protected visibility. As that up until now required a method to have a Bean annotation that was actually not possible.

This Commit introduces a method-annotation "@Ignore" to mark protected methods to be ignored as Bean-methods

### CODE REVIEW

**Comment by shochdoerfer** [comment]
Could you please share a gist with me to showcase what you want to achieve or where you were running into problems? Maybe we can find a better way of solving this. I am a bit reluctant when it comes to adding more annotations...

**Comment by heiglandreas** [comment]
Have a look [at this gist](https://gist.github.com/heiglandreas/dc9ed23f4ec3bbb997fd1bb4726080c1).

Depending on the environment I want to include either the `DevelopmentDependencies` or the `GlobalDependencies`. Due to type-hinting I created a method that returns a `ContainerInterface`-Contract to use it in multiple methods. That is not a problem when I use it only in `GlobalDependencies` as I can declare it `private` and everything is fine.

As I now would also like to use it in the `DevelopmentDependencies` I need to declare it at least `protected` to be able to use it there. But that then leads to a problem as every protected method will be exposed via an alias. So when there is no `@Bean` Annotation an Exception is thrown. To circumvent that (and still throw an Exception when someone forgot the `@Bean`-Annotation, I decided to add a new Annotation to clearly mark that this method should be ignored when it comes to creating Beans.

If you have a better solution I'm more than happy to use it.

**Comment by shochdoerfer** [comment]
In that specific use case I would use `BeanFactoryRegistry::getInstance();` in every method you need the container instance. Since the `BeanFactory` extends `ContainerInterface` that should not be a problem, or am I missing something?

If this still is a problem, I would rather think about of removing the required `@Bean` annotation from protected methods. But to be fair, I would need to think a bit about this and it's implications ;)

**Comment by heiglandreas** [comment]
In that specific use case that is an option. But when allowing private methods to be used within the class why am I not able to use protected methods? As private doesn't work in extended files :wink:

**Comment by shochdoerfer** [comment]
fair point. The original idea was to not extend config classes but I guess that does make sense. Would you mind to change the PR so that the @Bean annotation is optional for protected methods? And remove the @Ignore annotation logic you implemented?

**Comment by heiglandreas** [comment]
Sure! If that is an option it makes everything easier (I think…) :wink:

**Comment by shochdoerfer** [comment]
Thank you for your contribution!

**Pull request merged**
